/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    articles: Article;
    incidents: Incident;
    'community-contributions': CommunityContribution;
    reviews: Review;
    media: Media;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    incidents: IncidentsSelect<false> | IncidentsSelect<true>;
    'community-contributions': CommunityContributionsSelect<false> | CommunityContributionsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  publicName: string;
  bio?: string | null;
  /**
   * Reviewers can also write. Only administrators can change roles.
   */
  roles: ('admin' | 'reviewer' | 'author')[];
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Draft, review, and publish reported articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  eventDate: string;
  /**
   * A concise standfirst for cards and search results.
   */
  summary: string;
  /**
   * Markdown is rendered as formatted text; raw HTML is not published.
   */
  bodyMarkdown: string;
  authors?: (number | User)[] | null;
  /**
   * Use for guest or pseudonymous contributors who do not have an account.
   */
  byline?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  citations: {
    sourceTitle: string;
    publisher?: string | null;
    url: string;
    accessedAt: string;
    archiveUrl?: string | null;
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * Public corrections and clarifications. Never edit a published story silently — add a dated correction instead.
   */
  corrections?:
    | {
        note: string;
        issuedAt: string;
        id?: string | null;
      }[]
    | null;
  relatedIncidents?: (number | Incident)[] | null;
  topics?: ('public-spending' | 'environment' | 'justice' | 'labour' | 'land' | 'public-services')[] | null;
  /**
   * Authors may submit; reviewers decide; administrators publish.
   */
  workflowStatus: 'draft' | 'submitted' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'rejected';
  submittedBy?: (number | null) | User;
  publishedAt?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Verified incident records that power the notable list and timeline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents".
 */
export interface Incident {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  dateStart: string;
  dateEnd?: string | null;
  summary: string;
  notabilityReason: string;
  location?: string | null;
  /**
   * The public lifecycle of the case. This is separate from verification status.
   */
  caseStatus: 'newly-opened' | 'investigating' | 'accepting-contributions' | 'reviewing-contributions' | 'closed';
  /**
   * Opens the public contribution form for this case.
   */
  crowdsourcingEnabled?: boolean | null;
  verificationStatus: 'under-review' | 'disputed' | 'confirmed' | 'resolved';
  severity: 'low' | 'medium' | 'high';
  relatedArticles?: (number | Article)[] | null;
  citations: {
    sourceTitle: string;
    url: string;
    archiveUrl?: string | null;
    accessedAt: string;
    id?: string | null;
  }[];
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tips and evidence submitted by the public. Nothing is public until approved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-contributions".
 */
export interface CommunityContribution {
  id: number;
  incident: number | Incident;
  contributionType: 'document' | 'eyewitness' | 'data-tip' | 'correction' | 'context' | 'other';
  title: string;
  description: string;
  sourceUrl?: string | null;
  contributorName?: string | null;
  /**
   * Never displayed publicly.
   */
  contactEmail: string;
  publishName?: boolean | null;
  consentToReview: boolean;
  reviewStatus: 'received' | 'screening' | 'needs-info' | 'approved' | 'rejected';
  /**
   * Only takes effect after the contribution is approved.
   */
  publishInCase?: boolean | null;
  reviewerNotes?: string | null;
  reviewedBy?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private editorial decisions and feedback.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  article: number | Article;
  decision: 'approve' | 'changes_requested' | 'reject';
  /**
   * Visible to the submitting author and editorial staff.
   */
  comments: string;
  reviewer: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  visibility: 'private' | 'public';
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Append-only record of sensitive actions. Rows cannot be edited or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'pii-read' | 'contribution-status-change';
  actor?: (number | null) | User;
  targetCollection: string;
  targetId: string;
  /**
   * Short context, e.g. the previous and next review status.
   */
  details?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'incidents';
        value: number | Incident;
      } | null)
    | ({
        relationTo: 'community-contributions';
        value: number | CommunityContribution;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  publicName?: T;
  bio?: T;
  roles?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  eventDate?: T;
  summary?: T;
  bodyMarkdown?: T;
  authors?: T;
  byline?:
    | T
    | {
        name?: T;
        id?: T;
      };
  citations?:
    | T
    | {
        sourceTitle?: T;
        publisher?: T;
        url?: T;
        accessedAt?: T;
        archiveUrl?: T;
        note?: T;
        id?: T;
      };
  corrections?:
    | T
    | {
        note?: T;
        issuedAt?: T;
        id?: T;
      };
  relatedIncidents?: T;
  topics?: T;
  workflowStatus?: T;
  submittedBy?: T;
  publishedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents_select".
 */
export interface IncidentsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  dateStart?: T;
  dateEnd?: T;
  summary?: T;
  notabilityReason?: T;
  location?: T;
  caseStatus?: T;
  crowdsourcingEnabled?: T;
  verificationStatus?: T;
  severity?: T;
  relatedArticles?: T;
  citations?:
    | T
    | {
        sourceTitle?: T;
        url?: T;
        archiveUrl?: T;
        accessedAt?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-contributions_select".
 */
export interface CommunityContributionsSelect<T extends boolean = true> {
  incident?: T;
  contributionType?: T;
  title?: T;
  description?: T;
  sourceUrl?: T;
  contributorName?: T;
  contactEmail?: T;
  publishName?: T;
  consentToReview?: T;
  reviewStatus?: T;
  publishInCase?: T;
  reviewerNotes?: T;
  reviewedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  article?: T;
  decision?: T;
  comments?: T;
  reviewer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  visibility?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actor?: T;
  targetCollection?: T;
  targetId?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}